n1 = int(input("Digite um numero: "))
print(f"A tabuada desse número é: {n1*1}")
print(f"{n1*2}")
print(f"{n1*3}")
print(f"{n1*4}")
print(f"{n1*5}")
print(f"{n1*6}")
print(f"{n1*7}")
print(f"{n1*8}")
print(f"{n1*9}")
print(f"{n1*10}")